"""Compile structured form conditions; ASK only inside one visible screen.

The temporary screen context shares the loaded meaning graph's RDF store, but
the generated query cannot see its other contexts. Source triples are never
changed. Sentence blanks and their exact provenance stay in forms.py.
"""
from __future__ import annotations

from functools import lru_cache
import re
from time import perf_counter
from uuid import uuid4

from rdflib import Dataset, Graph, Literal, Namespace, RDF, URIRef
from rdflib.plugins.sparql import prepareQuery

from .graph import CONNECTION_PREFIX
from .meaning_graph import SPARQL_PARSE_LOCK, kind_node, word_node

SCREEN = Namespace('https://understood.app/nucleus/screen/')


@lru_cache(maxsize=512)
def _prepared_query(query: str):
    # The caller holds the shared parser lock, including cache misses. Parsed
    # query algebra is reused; each evaluation has its own screen initBinding.
    return prepareQuery(query)


def _check_when(when, kinds):
    from . import forms
    if not isinstance(when, dict) or not when or set(when) - forms.CONDITIONS:
        raise forms.Refused('unknown or missing conditions')
    kinds = forms.load_kinds() if kinds is None else kinds
    for name, value in when.items():
        if name == 'answer' and (not isinstance(value, str) or value not in forms.ANSWERS):
            raise forms.Refused('unknown answer label')
        if name in ('kinds_present', 'kinds_absent'):
            if (not isinstance(value, list) or not value or
                    any(not isinstance(k, str) or k not in kinds for k in value)):
                raise forms.Refused('unknown middle word')
            if len(set(value)) != len(value):
                raise forms.Refused('repeated middle word')
        if name in ('record_count', 'word_count') and not forms._valid_count(value):
            raise forms.Refused('invalid count condition')
        if name in ('missing_links', 'missing_why') and type(value) is not bool:
            raise forms.Refused(name + ' must be boolean')
    if set(when.get('kinds_present', [])) & set(when.get('kinds_absent', [])):
        raise forms.Refused('middle word both present and absent')


def compile_when(when: dict, *, kinds=None) -> str:
    """Canonical ASK generated by code, never a query supplied by a model.

    Legacy approved row forms retain exact-count support. Night proposal and
    middle-option validators continue to refuse those counts before this call.
    """
    _check_when(when, kinds)
    lines = ['PREFIX screen: <' + str(SCREEN) + '>', 'ASK WHERE {',
             '  GRAPH ?screen {', '    ?screen a screen:Screen .']
    for name in sorted(when):
        value = when[name]
        if name == 'answer':
            lines.append('    ?screen screen:answer ' + Literal(value).n3() + ' .')
        elif name in ('kinds_present', 'kinds_absent'):
            operator = 'EXISTS' if name == 'kinds_present' else 'NOT EXISTS'
            for kind in sorted(value):
                lines.append('    FILTER ' + operator + ' { ?word ' + kind_node(kind).n3() + ' ?record . }')
        elif name in ('record_count', 'word_count'):
            predicate = 'recordCount' if name == 'record_count' else 'wordCount'
            variable = '?' + name
            lines.append('    ?screen screen:' + predicate + ' ' + variable + ' .')
            if type(value) is int:
                comparison = variable + ' = ' + str(value)
            else:
                comparison = ' && '.join(variable + (' >= ' if bound == 'min' else ' <= ') + str(value[bound])
                                          for bound in ('min', 'max') if bound in value)
            lines.append('    FILTER (' + comparison + ')')
        elif name in ('missing_links', 'missing_why'):
            predicate = 'missingLinks' if name == 'missing_links' else 'missingWhy'
            lines.append('    ?screen screen:' + predicate + ' ' + Literal(value).n3() + ' .')
    return '\n'.join([*lines, '  }', '}'])


def _project(target: Graph, screen, context: URIRef):
    """Copy only the validated snapshot, keeping whole visible values as literals."""
    from . import forms_middle
    target.add((context, RDF.type, SCREEN.Screen))
    target.add((context, SCREEN.answer, Literal(screen.answer)))
    target.add((context, SCREEN.recordCount, Literal(len(screen.rows))))
    target.add((context, SCREEN.wordCount, Literal(len(screen.words))))
    target.add((context, SCREEN.missingLinks, Literal(screen.missing_links)))
    target.add((context, SCREEN.middleWordsComplete, Literal(screen.middle_words_complete)))
    gaps = [forms_middle.gap_span(why.text) for why in screen.whys]
    target.add((context, SCREEN.missingWhy, Literal(any(gaps))))
    for index, word in enumerate(screen.words):
        node = word_node(word)
        target.add((context, SCREEN.word, node))
        target.add((node, SCREEN.text, Literal(word)))
    for index, row in enumerate(screen.rows):
        node = URIRef(str(context) + '/row/' + str(index))
        record = URIRef(row.record if re.match(r'^[A-Za-z][A-Za-z0-9+.-]*:', row.record)
                        else CONNECTION_PREFIX + row.record)
        word = word_node(row.word)
        target.add((context, SCREEN.row, node))
        target.add((node, SCREEN.word, word))
        target.add((node, SCREEN.record, record))
        target.add((node, SCREEN.position, Literal(index)))
        target.add((node, SCREEN.source, Literal(f'screen.rows[{index}]')))
        target.add((record, SCREEN.recordId, Literal(row.record)))
        if row.kind is not None:
            predicate = kind_node(row.kind)
            target.add((node, SCREEN.kind, predicate))
            target.add((word, predicate, record))
        if row.quote is not None:
            target.add((record, SCREEN.quote, Literal(row.quote)))
    for index, meaning in enumerate(screen.meanings):
        node = URIRef(str(context) + '/meaning/' + str(index))
        target.add((context, SCREEN.meaning, node))
        target.add((node, SCREEN.word, word_node(meaning.word)))
        target.add((node, SCREEN.quote, Literal(meaning.quote)))
        target.add((node, SCREEN.source, Literal(f'screen.meanings[{index}].quote')))
    for index, why in enumerate(screen.whys):
        node = URIRef(str(context) + '/why/' + str(index))
        target.add((context, SCREEN.why, node))
        target.add((node, SCREEN.text, Literal(why.text)))
        target.add((node, SCREEN.source, Literal(f'screen.whys[{index}].text')))
        if gaps[index]:
            start, end = gaps[index]
            target.add((node, SCREEN.gap, Literal(why.text[start:end])))
    for word in screen.missing_words:
        target.add((context, SCREEN.missingWord, word_node(word)))


def matches(when: dict, screen, *, kinds=None, graph=None, query_trace=None) -> bool:
    """Execute the compiled ASK over one fresh named context, then remove it.

    graph may be the loaded meaning Dataset or Graph. With no engine document,
    isolated callers use a new Dataset and still execute real SPARQL. The trace
    receives total milliseconds for compilation, projection, ASK, and cleanup.
    """
    from . import forms
    started = perf_counter()
    dataset = context = None
    try:
        kinds = forms.load_kinds() if kinds is None else kinds
        forms._check_screen(screen, kinds)
        query = compile_when(when, kinds=kinds)
        if graph is not None and not isinstance(graph, Graph):
            raise forms.Refused('invalid meaning graph for form ASK')
        if isinstance(graph, Dataset):
            dataset = graph
        else:
            dataset = Dataset(store=graph.store) if graph is not None else Dataset()
        context = URIRef('urn:nucleus:screen:' + str(uuid4()))
        _project(dataset.graph(context), screen, context)
        with SPARQL_PARSE_LOCK:
            prepared = _prepared_query(query)
        return bool(dataset.query(prepared, initBindings={'screen': context}).askAnswer)
    except forms.Refused:
        raise
    except Exception as error:
        raise forms.Refused('form ASK failed: ' + str(error)) from error
    finally:
        try:
            if dataset is not None and context is not None:
                dataset.remove_graph(context)
        finally:
            if query_trace is not None:
                query_trace((perf_counter() - started) * 1000)
